Batardising couple of buildpacks

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,17 +1,267 @@
 #!/bin/bash
-# Usage: bin/compile <build-dir> <cache-dir>
 
 set -e
 set -o pipefail
+shopt -s dotglob
+
+basedir="$( cd -P "$( dirname "$0" )" && pwd )"
+source "$basedir/../conf/buildpack.conf"
+source $basedir/common.sh
+
+if [ -n "$BUILDPACK_DEBUG" ]; then
+    set -x
+fi
+
+BUILD_DIR="$1"
+CACHE_DIR="$2"
+
+cd "$BUILD_DIR"
+mkdir -p "$CACHE_DIR/package"
+
+function fetch_engine_package() {
+    local engine="$1"
+    local version="$2"
+    local location="$3"
+
+    fetch_package "${engine}-${version}" "$location"
+}
+
+function fetch_package() {
+    local package="$1"
+    local location="$2"
+
+    mkdir -p "$location"
+
+    local checksum_url="http://${S3_BUCKET}.s3.amazonaws.com/package/${package}.md5"
+    local package_url="http://${S3_BUCKET}.s3.amazonaws.com/package/${package}.tgz"
+    local checksum=$(curl "$checksum_url" 2> /dev/null)
+    local cache_checksum=
+
+    if [ -f "$CACHE_DIR/package/${package}.md5" ]; then
+        local cache_checksum=$(cat "$CACHE_DIR/package/${package}.md5")
+    fi
+
+    mkdir -p "$CACHE_DIR/package/$(dirname "$package")"
+
+    if [ "$cache_checksum" != "$checksum" ]; then
+        curl "$package_url" -L -s > "$CACHE_DIR/package/${package}.tgz"
+        echo "$checksum" > "$CACHE_DIR/package/${package}.md5"
+    else
+        echo "Checksums match. Fetching from cache."
+    fi
+
+    tar xzf "$CACHE_DIR/package/${package}.tgz" -C "$location"
+}
+
+function log_error() {
+    local c='s/^/ !     /'
+    case $(uname) in
+        Darwin) echo "$*" | sed -l "$c";;
+        *)      echo "$*" | sed -u "$c";;
+    esac
+}
+
+function indent() {
+    local c='s/^/       /'
+    case $(uname) in
+        Darwin) sed -l "$c";;
+        *)      sed -u "$c";;
+    esac
+}
+
+function install_composer_deps() {
+    local cwd=$(pwd)
+    local target="$1"
+
+    if [ ! -f "$target/composer.json" ]; then
+        return 0
+    fi
+
+    if [ ! -f "$target/composer.lock" ]; then
+        log_error "Lockfile required. Please check it in."
+        return 1
+    fi
+
+    export COMPOSER_CACHE_DIR=$CACHE_DIR/composer
+    mkdir -p $COMPOSER_CACHE_DIR
+    mkdir -p "$target/vendor/composer/bin"
+
+    local checksum=$(curl --silent "http://${S3_BUCKET}.s3.amazonaws.com/composer/composer.phar.md5")
+
+    status "Vendoring Composer"
+    if [ ! -f "$CACHE_DIR/composer.phar.md5" ] || [ "$(cat $CACHE_DIR/composer.phar.md5)" != "$checksum" ]; then
+        echo "Updating Composer" | indent
+        curl --silent "http://${S3_BUCKET}.s3.amazonaws.com/composer/composer.phar" > "$CACHE_DIR/composer.phar" | indent
+        chmod a+x "$CACHE_DIR/composer.phar"
+        echo "$checksum" > $CACHE_DIR/composer.phar.md5
+    fi
+
+    cp "$CACHE_DIR/composer.phar" "$target/vendor/composer/bin/"
+
+    local required_extensions=$(jq --raw-output '.require | keys | .[]' < "$BUILD_DIR/composer.json" | grep '^ext-' | sed 's/^ext-//')
+    if [ -n "$required_extensions" ]; then
+        status "Bundling additional extensions $required_extensions"
+        for ext in $required_extensions; do
+            echo "$ext" | indent
+            # TODO: Find a better way to ignore extensions which were not found in S3
+            fetch_package "ext/$(php_api_version)/php-${ext}" "/app/vendor/php" 2>/dev/null || true | indent
+        done
+    fi
+
+    php "vendor/composer/bin/composer.phar" self-update
+
+    status "Installing application dependencies with Composer"
+    {
+        cd "$target"
+        php "vendor/composer/bin/composer.phar" install \
+            --prefer-dist \
+            --optimize-autoloader \
+            --no-interaction \
+            --no-dev
+        cd "$cwd"
+    } | indent
+}
+
+function install_node_deps() {
+    local cwd=$(pwd)
+    local target="$1"
+
+    if [ ! -f "$target/package.json" ]; then
+        return 0
+    fi
+
+    status "NODE (package.json) app detected"
+
+    source ${basedir}/compile_node $BUILD_DIR $CACHE_DIR
+
+    local node_path='vendor/node'
+
+    # Symlink node to /app/vendor/node so node and its modules are runnable.
+
+    ln -s ${BUILD_DIR}/${node_path}/ /app/${node_path}
+    ln -s ${BUILD_DIR}/node_modules /app/node_modules
+
+    echo "Node " `node -v` | indent
+}
+
+export_env_dir() {
+    env_dir=$1
+    blacklist_regex=${3:-'^(PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH|LD_LIBRARY_PATH)$'}
+    if [ -d "$env_dir" ]; then
+        for e in $(ls $env_dir); do
+            echo "$e" | grep -qvE "$blacklist_regex" &&
+            export "$e=$(cat $env_dir/$e)"
+            :
+        done
+    fi
+}
+
+function mktmpdir() {
+    dir=$(mktemp -t php-$1-XXXX)
+    rm -rf $dir
+    mkdir -p $dir
+    echo $dir
+}
+
+function php_api_version() {
+    basename "$(php-config --extension-dir)" | tr '-' ' ' | cut -f 5 -d ' '
+}
+
+function package_document_root() {
+    jq --raw-output '.extra.heroku["document-root"] // ""' < "$BUILD_DIR/composer.json"
+}
+
+function package_index_file() {
+    jq --raw-output '.extra.heroku["index-document"] // "index.php"' < "$BUILD_DIR/composer.json"
+}
+
+function package_framework() {
+    jq --raw-output '.extra.heroku.framework // ""' < "$BUILD_DIR/composer.json"
+}
+
+function package_nginx_version() {
+    jq --raw-output ".extra.heroku.engines.nginx // \"default\"" < "$BUILD_DIR/composer.json"
+}
+
+function package_php_version() {
+    jq --raw-output ".extra.heroku.engines.php // \"default\"" < "$BUILD_DIR/composer.json"
+}
+
+function package_php_config() {
+    jq --raw-output '.extra.heroku["php-config"] // [] | .[]' < "$BUILD_DIR/composer.json"
+}
+
+function package_php_includes() {
+    jq --raw-output '.extra.heroku["php-includes"] // [] | .[]' < "$BUILD_DIR/composer.json"
+}
+
+function package_nginx_includes() {
+    jq --raw-output '.extra.heroku["nginx-includes"] // [] | .[]' < "$BUILD_DIR/composer.json"
+}
+
+function package_log_files() {
+    jq --raw-output '.extra.heroku["log-files"] // [] | .[]' < "$BUILD_DIR/composer.json"
+}
+
+function package_compile_cmd() {
+    jq --raw-output '.extra.heroku["compile"] // [] | .[]' < "$BUILD_DIR/composer.json"
+}
+
+function package_newrelic_enabled() {
+    local val=$(jq --raw-output '.extra.heroku["newrelic"] // false' < "$BUILD_DIR/composer.json")
+
+    if [ "$val" = "true" ]; then
+        return 0
+    else
+        return 1
+    fi
+}
+
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
+
+function check_md5() {
+  SUMS_FILE="${BUNDLE_DIR}/${MANIFEST_FILE}"
+  TARGET="$1"
+  SUM=`cat "${SUMS_FILE}" | grep "${TARGET}" | cut -d ' ' -f 1`
+  OUTPUT=`md5sum ${BUNDLE_DIR}/${TARGET} | cut -d ' ' -f 1`
+  ! [ "$SUM" = "$OUTPUT" ]
+}
+
+function download_url() {
+  TARGET_URL="$1"
+  curl -s -S -O -L -m 300 --connect-timeout 60 "$TARGET_URL"
+}
+
+export_env_dir "$3"
+
+
+# Download jq binary for JSON processing
+export PATH="$HOME/bin:$PATH"
+curl "http://${S3_BUCKET}.s3.amazonaws.com/bin/jq" -L -s -o - > "$HOME/bin/jq"
+chmod +x "$HOME/bin/jq"
+
 
 # START CONFIG
-S3_BUCKET=yg-php-buildpack-opi
 S3_URL="https://s3.amazonaws.com/${S3_BUCKET}"
 NGINX_VERSION=1.6.0
 PHP_VERSION=5.5.15
 NEWRELIC_VERSION=4.10.1.62
 MEMCACHED_VERSION=1.4.20
 REPO_URL=${S3_URL}
+
+DOCUMENT_ROOT=
+INDEX_DOCUMENT="index.php"
+PHP_EXTRA_CONFIG=
+PHP_INCLUDES=
+COMPILE_CMD=
+NGINX_INCLUDES=
+LOG_FILES=( "/app/vendor/nginx/logs/access.log" "/app/vendor/nginx/logs/error.log" "/app/vendor/php/var/log/error.log" )
 # END CONFIG
 
 MANIFEST_FILE="manifest.md5sum"
@@ -26,38 +276,24 @@ PHP_URL="${REPO_URL}/${PHP_FILE}"
 PHP_LIBS_URL="${REPO_URL}/${PHP_LIBS_FILE}"
 MEMCACHED_URL="${REPO_URL}/${MEMCACHED_FILE}"
 COMPOSER_URL="http://getcomposer.org/composer.phar"
-#
 
-function indent() {
-	c='s/^/       /'
-	case $(uname) in
-		Darwin) sed -l "$c";;
-		*)      sed -u "$c";;
-	esac
-}
 
-function check_md5() {
-	SUMS_FILE="${BUNDLE_DIR}/${MANIFEST_FILE}"
-	TARGET="$1"
-	SUM=`cat "${SUMS_FILE}" | grep "${TARGET}" | cut -d ' ' -f 1`
-	OUTPUT=`md5sum ${BUNDLE_DIR}/${TARGET} | cut -d ' ' -f 1`
-	! [ "$SUM" = "$OUTPUT" ]
-}
 
-function download_url() {
-	TARGET_URL="$1"
-	curl -s -S -O -L -m 300 --connect-timeout 60 "$TARGET_URL"
-}
+# Read config variables from composer.json if it exists
+if [ -f "$BUILD_DIR/composer.json" ]; then
+    DOCUMENT_ROOT=$(package_document_root)
+    INDEX_DOCUMENT=$(package_index_file)
+    PHP_EXTRA_CONFIG=$(package_php_config)
+    PHP_INCLUDES=$(package_php_includes)
+    COMPILE_CMD=$(package_compile_cmd)
+    NGINX_INCLUDES=$(package_nginx_includes)
+    USER_LOG_FILES=$(package_log_files)
+fi
 
-BIN_DIR=$(dirname $0)
-BUILD_DIR=$1
-CACHE_DIR=$2
-BUNDLE_DIR="${CACHE_DIR}/bundles"
-LP_DIR=`cd $(dirname $0); cd ..; pwd`
-export COMPOSER_HOME="${CACHE_DIR}/.composer"
+[ ! -d "$BUILD_DIR/vendor" ] && mkdir -p "$BUILD_DIR/vendor"
 
-# include .files when moving things around
-shopt -s dotglob
+
+#################### INSTALL STUFF
 
 mkdir -p $BUILD_DIR $CACHE_DIR ${BUNDLE_DIR} ${BUILD_DIR}/local ${BUILD_DIR}/vendor/bin ${COMPOSER_HOME} ${BUILD_DIR}/.profile.d
 
@@ -162,114 +398,91 @@ mkdir -p ${BUILD_DIR}/vendor/memcached
 tar xzf ${MEMCACHED_FILE} -C ${BUILD_DIR}/vendor/memcached
 export PATH="${PATH}:${BUILD_DIR}/vendor/memcached/bin"
 
-# Composer Installation
-pushd ${BUILD_DIR} > /dev/null
-if [ -f "composer.json" ]
-then
-	echo "-----> Installing dependencies using Composer"
-	GIT_DIR_ORIG=${GIT_DIR}
-	unset GIT_DIR
 
-	if [ ! -f "composer.phar" ]
-	then
-		echo "Fetching composer.phar" | indent
-		echo ${COMPOSER_URL} | indent
-		download_url ${COMPOSER_URL}
-	fi
+#######################################
 
-	# do the deed!
-	echo "Running: php composer.phar install" | indent
-	LD_LIBRARY_PATH="${BUILD_DIR}/local/lib" ${BUILD_DIR}/vendor/php/bin/php composer.phar install -n | indent
 
-	export GIT_DIR=${GIT_DIR_ORIG}
-fi
-popd > /dev/null
+test ! -d ".profile.d" && mkdir -p .profile.d || true
 
-# Config files
-echo "-----> Copying config files"
-cp $LP_DIR/conf/php-fpm.conf ${BUILD_DIR}/vendor/php/etc/php-fpm.conf
-cp ${BUILD_DIR}/vendor/php/php/fpm/status.html ${BUILD_DIR}/status.html
-cp $LP_DIR/conf/php.ini ${BUILD_DIR}/vendor/php/php.ini
-cp -a $LP_DIR/conf/etc.d ${BUILD_DIR}/vendor/php/
-cp $LP_DIR/conf/nginx.conf.erb ${BUILD_DIR}/vendor/nginx/conf/nginx.conf.erb
-cp -n ${LP_DIR}/.profile.d/* ${BUILD_DIR}/.profile.d/
-#erb $LP_DIR/conf/nginx.conf.erb > ${BUILD_DIR}/vendor/nginx/conf/nginx.conf
+cat > ".profile.d/php.sh" <<SH
+export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/app/bin:/app/vendor/nginx/sbin:/app/vendor/php/sbin:/app/vendor/php/bin:/app/vendor/bin:\$PATH
+export HEROKU_BUILD_TIME=$(date +%Y%m%d%H%M%S)
+SH
 
-# newrelic
-echo "-----> Installing newrelic"
-if [ -f "${NEWRELIC_FILE}" ]
-then
-	sed -i "s/__APPNAME__/${NEW_RELIC_APPNAME}/g" ${BUILD_DIR}/vendor/php/etc.d/05_newrelic.ini
-	sed -i "s/__LICENSE__/${NEW_RELIC_LICENSE_KEY}/g" ${BUILD_DIR}/vendor/php/etc.d/05_newrelic.ini
+source ".profile.d/php.sh"
+
+if [ -f "$BUILD_DIR/composer.json" ] && package_newrelic_enabled; then
+	 cp -f "$basedir/../conf/php/newrelic.ini" "/app/vendor/php/etc/conf.d/newrelic.ini"
 fi
 
-echo "-----> Installing boot script"
-cd $BUILD_DIR
-cat >>boot.sh <<EOF
-#!/usr/bin/env bash
+mkdir -p "conf"
+cp "$basedir/../conf/nginx/base.conf.erb" "conf/nginx.conf.erb"
+cp "$basedir/../conf/php/php-fpm.conf" "/app/vendor/php/etc/php-fpm.conf"
+cp "$basedir/../conf/php/php.ini" "/app/vendor/php/etc/php.ini"
 
-echo "Booting nginx"
+pear config-set php_ini /app/vendor/php/etc/php.ini &> /dev/null
 
-# Override config files if provided in app.
-if [ -d /app/conf ]; then
-
-	mkdir -p /app/conf/nginx.d
-
-	if [ -d /app/conf/etc.d ]; then
-		cp -f /app/conf/etc.d/* /app/vendor/php/etc.d/
-	fi
-
-	if [ -r /app/conf/php-fpm.conf ]; then
-		cp -f /app/conf/php-fpm.conf /app/vendor/php/etc/php-fpm.conf
-	fi
-
-	if [ -r /app/conf/php.ini ]; then
-		cp -f /app/conf/php.ini /app/vendor/php/php.ini
-	fi
-
-	if [ -r /app/conf/nginx.conf.erb ]; then
-		cp -f /app/conf/nginx.conf.erb /app/vendor/nginx/conf/nginx.conf.erb
-	fi
-
-fi
-
-# Set correct port variable.
-erb /app/vendor/nginx/conf/nginx.conf.erb > /app/vendor/nginx/conf/nginx.conf
-
-if [ -d /app/conf/nginx.d ]; then
-	# Parse .erb into .conf.
-	for f in /app/conf/nginx.d/*.erb
-	do
-		if [ -r "\${f}" ];
-		then
-			erb "\${f}" > "\${f}.conf"
-		fi
-	done
-fi
-
-# Preserve current php-fpm.conf so that env list does
-# not go out of hand across restarts.
-if [ -r /app/vendor/php/etc/php-fpm.conf.current ]; then
-	cp -f /app/vendor/php/etc/php-fpm.conf.current /app/vendor/php/etc/php-fpm.conf
-else
-	cp -f /app/vendor/php/etc/php-fpm.conf /app/vendor/php/etc/php-fpm.conf.current
-fi
-
-# Expose Heroku config vars to PHP-FPM processes
-for var in \`env | cut -f1 -d=\`; do
-	echo "env[\$var] = \\$\${var}" >> /app/vendor/php/etc/php-fpm.conf
+for conf in $PHP_EXTRA_CONFIG; do
+    echo "$conf" >> "/app/vendor/php/etc/php.ini"
 done
 
-mkdir -p /app/local/var/log/newrelic
-mkdir -p client_body_temp fastcgi_temp proxy_temp scgi_temp uwsgi_temp /app/php/opigram/application/logs/ /app/php/admin/application/logs/
-touch /app/vendor/nginx/logs/access.log /app/vendor/nginx/logs/error.log /app/vendor/php/var/log/php-fpm.log /app/vendor/php/var/log/application.log /app/vendor/php/var/log/php-errors.log /app/local/var/log/newrelic/newrelic-daemon.log /app/local/var/log/newrelic/php_agent.log
-touch /app/php/opigram/application/logs/application.log /app/php/admin/application/logs/application.log
-(tail -f -n 0 /app/vendor/nginx/logs/*.log /app/vendor/php/var/log/*.log /app/local/var/log/newrelic/*.log /app/php/*/application/logs/*.log &)
+for include in $PHP_INCLUDES; do
+    cp "$BUILD_DIR/$include" "/app/vendor/php/etc/conf.d/"
+done
 
-/app/vendor/memcached/bin/memcached -u nobody -d -p 11211 -U 112211 -m 64
-/app/vendor/php/sbin/php-fpm
-/app/vendor/nginx/sbin/nginx
-EOF
-chmod +x boot.sh
+install_node_deps "$BUILD_DIR"
+install_composer_deps "$BUILD_DIR"
 
-echo "-----> Done with compile"
+if [ -n "$COMPILE_CMD" ]; then
+    status "Running compile commands"
+    while read -r cmd; do
+        echo "Running '$cmd'" | indent
+        eval $cmd             | indent
+    done <<< "$COMPILE_CMD"
+fi
+
+mkdir -p "bin"
+
+cat > "bin/run" <<SH
+#!/usr/bin/env bash
+
+pmsgr=/tmp/pmsgr
+rm -f \$pmsgr
+mkfifo \$pmsgr
+
+for var in \`env | cut -f1 -d=\`; do
+    echo "env[\$var] = \\$\${var}" >> /app/vendor/php/etc/php-fpm.conf
+done
+
+export DOCUMENT_ROOT="$DOCUMENT_ROOT"
+export INDEX_DOCUMENT="$INDEX_DOCUMENT"
+export NGINX_INCLUDES="$NGINX_INCLUDES"
+
+if [ -n "\$NEW_RELIC_LICENSE_KEY" ]; then
+    echo "newrelic.license=\"\$NEW_RELIC_LICENSE_KEY\"" >> /app/vendor/php/etc/conf.d/newrelic.ini
+    echo "newrelic.appname=\"\$NEW_RELIC_APPNAME\"" >> /app/vendor/php/etc/conf.d/newrelic.ini
+fi
+
+erb conf/nginx.conf.erb > /app/vendor/nginx/conf/nginx.conf
+erb conf/site.conf.erb > /app/vendor/nginx/conf/site.conf
+
+`init_log_plex_fifo ${LOG_FILES}`
+`tail_log_plex ${LOG_FILES} ${SYS_LOG_FILES}`
+
+(
+    exec php-fpm -p "/app/vendor/php"
+    \$pmsgr < "php-fpm"
+)&
+
+(
+    exec nginx -p "/app/vendor/nginx" -c /app/vendor/nginx/conf/nginx.conf
+    \$pmsgr < "nginx"
+)&
+
+
+read exitproc <\$pmsgr
+echo "Boot failed: \$exitproc"
+exit 1
+SH
+
+chmod +x "bin/run"
